--- # DELEGATE TO FUNCTION DEMO
- hosts: apacheweb
  sudo: yes
  user: test
  connection: ssh
  tasks:
  - name: Run a remote ping on the application server
    command: ping -c 4 raspberrypi-3 > /home/test/Playbooks/ping.out
    delegate_to: 127.0.0.1
  - name: Install a package 
    apt: pkg=lynx state=latest
