--- # GIT MODULE EXAMPLE
- hosts: apacheweb
  user: test
  connection: ssh
  gather_facts: no
  tasks:
  - name: Checking out a git repo on the remote server
    git: repo=ssh://test@raspberrypi-1/home/test/Playbooks dest=/home/test/gitrepo
