--- # My First YAML Playbook for Ansible
- hosts: apacheweb
  user: test
  sudo: yes
  connection: ssh
  gather_facts: no
  vars:
    playbook_version: 0.1b
  vars_files:
    - conf/copyright.yml
    - conf/webdefaults.yml
  vars_prompt:
    - name: pkg_name
      prompt: Install Which Package?
  tasks:
    - name: Install Apache Web Server
      action: apt name=apache2 state=installed
      notify: Restart HTTPD
  handlers:
    - name: Restart HTTPD
      action: service name=apache2 state=restarted

